#!/bin/bash

SELF=`dirname $0`
SCRIPT_DIR=`readlink -f $0`
TEMPLATE_DIR=`dirname $SCRIPT_DIR`/templates

usage_exit() {
    echo "Usage: $0 [-a] [-l lang] item ..." 1>&2
    echo "Available languages are:" 
    ls -x $TEMPLATE_DIR | sed "N;s/\n/, /m" | sed "s/\.template//g"
    exit 1
}

if [ "$1" = "" ]; then
    usage_exit
fi

while getopts al:h OPT
do
    case $OPT in
        a)  FLAG_A=1
            ;;
        l)  TARGET_LANG=$OPTARG
            ;;
        h)  usage_exit
            ;;
        \?) usage_exit
            ;;
    esac
done

TEMPLATE=$TEMPLATE_DIR/$TARGET_LANG.template
if [ ! -f $TEMPLATE ]; then
    echo "$TARGET_LANG.template does not exist."
    exit 1
fi

cat $TEMPLATE
